import { DEMO_PASSWORD, LOGIN_ID_BY_USER_ID } from "./demo-accounts";
import { hashPassword } from "./hash";
import type { Question, StoreData, User } from "./types";

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

export function createSeedUsers(): User[] {
  const studentHash = hashPassword(DEMO_PASSWORD.student);
  const teacherHash = hashPassword(DEMO_PASSWORD.teacher);
  const adminHash = hashPassword(DEMO_PASSWORD.admin);
  const createdAt = hoursAgo(24 * 40);

  const users = [
    {
      id: "u-student-1",
      loginId: LOGIN_ID_BY_USER_ID["u-student-1"],
      passwordHash: studentHash,
      name: "山田 花子",
      role: "student",
      grade: "2年",
      homeroom: "2年A組",
    },
    {
      id: "u-student-2",
      loginId: LOGIN_ID_BY_USER_ID["u-student-2"],
      passwordHash: studentHash,
      name: "佐藤 太郎",
      role: "student",
      grade: "2年",
      homeroom: "2年B組",
    },
    {
      id: "u-student-3",
      loginId: LOGIN_ID_BY_USER_ID["u-student-3"],
      passwordHash: studentHash,
      name: "斎藤 陽菜",
      role: "student",
      grade: "1年",
      homeroom: "1年C組",
    },
    {
      id: "u-student-4",
      loginId: LOGIN_ID_BY_USER_ID["u-student-4"],
      passwordHash: studentHash,
      name: "加藤 蓮",
      role: "student",
      grade: "3年",
      homeroom: "3年A組",
    },
    {
      id: "u-math-a",
      loginId: LOGIN_ID_BY_USER_ID["u-math-a"],
      passwordHash: teacherHash,
      name: "田中 美咲",
      role: "teacher",
      subjects: ["数学"],
      specialties: ["二次関数", "微分・積分", "三角関数"],
      availability: "available",
      note: "放課後は職員室にいます",
    },
    {
      id: "u-math-b",
      loginId: LOGIN_ID_BY_USER_ID["u-math-b"],
      passwordHash: teacherHash,
      name: "鈴木 健一",
      role: "teacher",
      subjects: ["数学"],
      specialties: ["確率", "図形", "場合の数"],
      availability: "soon",
      availableInMinutes: 10,
      note: "今は授業中。10分後に戻ります",
    },
    {
      id: "u-english",
      loginId: LOGIN_ID_BY_USER_ID["u-english"],
      passwordHash: teacherHash,
      name: "高橋 恵",
      role: "teacher",
      subjects: ["英語"],
      specialties: ["関係詞", "仮定法", "長文読解"],
      availability: "available",
      note: "質問は短くまとめてくれると助かります",
    },
    {
      id: "u-japanese",
      loginId: LOGIN_ID_BY_USER_ID["u-japanese"],
      passwordHash: teacherHash,
      name: "伊藤 誠",
      role: "teacher",
      subjects: ["国語"],
      specialties: ["現代文", "古文"],
      availability: "busy",
      note: "会議中です",
    },
    {
      id: "u-science",
      loginId: LOGIN_ID_BY_USER_ID["u-science"],
      passwordHash: teacherHash,
      name: "中村 理沙",
      role: "teacher",
      subjects: ["理科"],
      specialties: ["化学", "物理"],
      availability: "off",
      note: "本日の質問受付は終了しました",
    },
    {
      id: "u-social",
      loginId: LOGIN_ID_BY_USER_ID["u-social"],
      passwordHash: teacherHash,
      name: "小林 直人",
      role: "teacher",
      subjects: ["社会"],
      specialties: ["日本史", "世界史"],
      availability: "available",
    },
    {
      id: "u-admin",
      loginId: LOGIN_ID_BY_USER_ID["u-admin"],
      passwordHash: adminHash,
      name: "管理 太郎",
      role: "admin",
    },
  ];

  return users.map((user) => ({
    ...user,
    status: "active" as const,
    createdAt,
    className: user.homeroom?.match(/([A-D])組/)?.[1],
  })) as User[];
}

const STATUS_MAP = {
  open: "matched",
  queued: "deferred",
  assigned: "accepted",
} as const;

function q(partial: Omit<Question, "transferHistory" | "classifyReasons" | "suggestedTeacherIds" | "events" | "questionType"> & Partial<Question>): Question {
  const status = (STATUS_MAP as Record<string, Question["status"]>)[partial.status] ?? partial.status;
  const events = partial.events ?? [
    {
      type: "submitted" as const,
      at: partial.createdAt,
      actorId: partial.studentId,
      message: "質問を投稿しました",
    },
    {
      type: "classified" as const,
      at: partial.createdAt,
      message: `${partial.subject} / ${partial.topic} として整理しました`,
    },
  ];
  if (!partial.events && partial.assignedTeacherId) {
    events.push({
      type: status === "accepted" ? "accepted" : "matched",
      at: partial.createdAt,
      message:
        status === "accepted" ? "先生が質問を受け付けました" : "先生の待ち行列に入れました",
    });
  }
  if (!partial.events && status === "answered") {
    events.push({
      type: "answered",
      at: partial.answeredAt ?? partial.createdAt,
      actorId: partial.answeredBy,
      message: "先生から回答が届きました",
    });
  }
  if (!partial.events && status === "deferred") {
    events.push({
      type: "deferred",
      at: partial.createdAt,
      message: "先生が、あとで対応するとしました",
    });
  }
  return {
    transferHistory: [],
    classifyReasons: ["確認用の蓄積データです。"],
    suggestedTeacherIds: [],
    questionType: partial.questionType ?? "解法",
    ...partial,
    status,
    events: partial.events ?? events,
  };
}

export function createSeedQuestions(): Question[] {
  return [
    q({
      id: "q-1",
      studentId: "u-student-1",
      body: "二次関数 y = -2x^2 + 8x + 1 の最大値の求め方がわかりません。平方完成でよいのでしょうか。",
      createdAt: hoursAgo(2),
      subject: "数学",
      topic: "二次関数",
      summary: "二次関数の最大値の求め方",
      urgency: "normal",
      recommendedDept: "数学科",
      status: "open",
      assignedTeacherId: "u-math-a",
      suggestedTeacherIds: ["u-math-a", "u-math-b"],
    }),
    q({
      id: "q-2",
      studentId: "u-student-2",
      body: "関係代名詞 which と that の使い分けが分かりません。制限用法のときどう違うのでしょう。",
      createdAt: hoursAgo(5),
      subject: "英語",
      topic: "関係詞",
      summary: "関係代名詞 which と that の使い分け",
      urgency: "normal",
      recommendedDept: "英語科",
      status: "assigned",
      assignedTeacherId: "u-english",
      suggestedTeacherIds: ["u-english"],
    }),
    q({
      id: "q-3",
      studentId: "u-student-3",
      body: "サイコロを2回振って出た目の和が偶数になる確率を求める問題が解けません。",
      createdAt: hoursAgo(8),
      subject: "数学",
      topic: "確率",
      summary: "サイコロの和が偶数になる確率",
      urgency: "high",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-b",
      suggestedTeacherIds: ["u-math-b", "u-math-a"],
      answer:
        "和が偶数になるのは（偶数,偶数）または（奇数,奇数）です。それぞれ 3/6 × 3/6 なので、3/6×3/6 + 3/6×3/6 = 1/2 です。授業後に図でも確認しましょう。",
      answeredAt: hoursAgo(6),
      answeredBy: "u-math-b",
    }),
    q({
      id: "q-4",
      studentId: "u-student-4",
      body: "仮定法過去の If I were you は、なぜ was ではなく were なのですか。明日小テストです。",
      createdAt: hoursAgo(12),
      subject: "英語",
      topic: "仮定法",
      summary: "仮定法過去の were",
      urgency: "high",
      recommendedDept: "英語科",
      status: "answered",
      assignedTeacherId: "u-english",
      suggestedTeacherIds: ["u-english"],
      answer:
        "仮定法過去では、be動詞は人称に関係なく were を使うのが原則です。口語では was も出ますが、テストでは were を覚えてください。",
      answeredAt: hoursAgo(10),
      answeredBy: "u-english",
    }),
    q({
      id: "q-5",
      studentId: "u-student-1",
      body: "円に内接する三角形の証明問題で、相似の使いどころがわかりません。",
      createdAt: hoursAgo(20),
      subject: "数学",
      topic: "図形",
      summary: "円に内接する三角形の証明",
      urgency: "normal",
      recommendedDept: "数学科",
      status: "queued",
      assignedTeacherId: "u-math-b",
      suggestedTeacherIds: ["u-math-b"],
    }),
    q({
      id: "q-6",
      studentId: "u-student-2",
      body: "長文読解で内容一致問題を解くとき、本文のどこを見るのが効率的ですか。",
      createdAt: hoursAgo(26),
      subject: "英語",
      topic: "長文読解",
      summary: "長文の内容一致問題の解き方",
      urgency: "low",
      recommendedDept: "英語科",
      status: "answered",
      assignedTeacherId: "u-english",
      suggestedTeacherIds: ["u-english"],
      answer: "設問のキーワードを先に拾い、該当パラグラフだけ精読すると速いです。全部を同じ密度で読まなくて大丈夫です。",
      answeredAt: hoursAgo(24),
      answeredBy: "u-english",
    }),
    q({
      id: "q-7",
      studentId: "u-student-3",
      body: "二次関数の頂点の座標を求める公式は覚えたのですが、なぜそうなるのか説明できません。",
      createdAt: hoursAgo(30),
      subject: "数学",
      topic: "二次関数",
      summary: "二次関数の頂点公式の意味",
      urgency: "normal",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-a",
      suggestedTeacherIds: ["u-math-a"],
      answer: "平方完成すると y = a(x-p)^2 + q の形になり、(p, q) が頂点です。公式はその変形を省略したものです。",
      answeredAt: hoursAgo(28),
      answeredBy: "u-math-a",
    }),
    q({
      id: "q-8",
      studentId: "u-student-4",
      body: "モル濃度の計算で、溶液の体積をリットルに直すのを忘れがちです。化学のこの単元が苦手です。",
      createdAt: hoursAgo(36),
      subject: "理科",
      topic: "化学",
      summary: "モル濃度の計算",
      urgency: "normal",
      recommendedDept: "理科",
      status: "queued",
      assignedTeacherId: "u-science",
      suggestedTeacherIds: ["u-science"],
    }),
    q({
      id: "q-9",
      studentId: "u-student-1",
      body: "古文の助動詞「けり」の意味の見分け方が分かりません。",
      createdAt: hoursAgo(40),
      subject: "国語",
      topic: "古文",
      summary: "助動詞けりの識別",
      urgency: "normal",
      recommendedDept: "国語科",
      status: "open",
      assignedTeacherId: "u-japanese",
      suggestedTeacherIds: ["u-japanese"],
    }),
    q({
      id: "q-10",
      studentId: "u-student-2",
      body: "明治維新の年表が頭に入りません。戊辰戦争の流れを教えてほしいです。",
      createdAt: hoursAgo(44),
      subject: "社会",
      topic: "日本史",
      summary: "明治維新と戊辰戦争",
      urgency: "low",
      recommendedDept: "社会科",
      status: "answered",
      assignedTeacherId: "u-social",
      suggestedTeacherIds: ["u-social"],
      answer: "大政奉還→王政復古→鳥羽・伏見→江戸開城、の順で押さえると流れが見えます。授業プリントの年表と合わせて確認しましょう。",
      answeredAt: hoursAgo(42),
      answeredBy: "u-social",
    }),
    q({
      id: "q-11",
      studentId: "u-student-3",
      body: "場合の数で、重複を除くのが難しいです。確率の問題の前に整理したいです。",
      createdAt: hoursAgo(50),
      subject: "数学",
      topic: "確率",
      summary: "場合の数の重複",
      urgency: "normal",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-b",
      suggestedTeacherIds: ["u-math-b"],
      answer: "「同じものを区別するか」を先に決めると重複が減ります。樹形図を一度書いてから公式に戻るとよいです。",
      answeredAt: hoursAgo(48),
      answeredBy: "u-math-b",
    }),
    q({
      id: "q-12",
      studentId: "u-student-4",
      body: "二次関数の最大・最小で、定義域が限られているときの場合分けが苦手です。",
      createdAt: hoursAgo(55),
      subject: "数学",
      topic: "二次関数",
      summary: "定義域つき二次関数の最大最小",
      urgency: "high",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-a",
      suggestedTeacherIds: ["u-math-a"],
      answer: "軸が定義域の中か外かで場合分けします。軸が中なら頂点、外なら端点だけ見れば足ります。",
      answeredAt: hoursAgo(53),
      answeredBy: "u-math-a",
    }),
    q({
      id: "q-13",
      studentId: "u-student-1",
      body: "関係詞の非制限用法でカンマの前に that が使えない理由を忘れました。",
      createdAt: hoursAgo(60),
      subject: "英語",
      topic: "関係詞",
      summary: "非制限用法と that",
      urgency: "normal",
      recommendedDept: "英語科",
      status: "answered",
      assignedTeacherId: "u-english",
      suggestedTeacherIds: ["u-english"],
      answer: "非制限用法は「追加情報」なので、接続詞に近い which / who を使います。that は制限用法専用と覚えると安全です。",
      answeredAt: hoursAgo(58),
      answeredBy: "u-english",
    }),
    q({
      id: "q-14",
      studentId: "u-student-2",
      body: "図形の相似比と面積比の関係を、テスト前に確認したいです。明日定期テストです。",
      createdAt: hoursAgo(70),
      subject: "数学",
      topic: "図形",
      summary: "相似比と面積比",
      urgency: "high",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-b",
      suggestedTeacherIds: ["u-math-b"],
      answer: "相似比が a:b なら、面積比は a²:b²、体積比は a³:b³ です。単位が長さか面積かを先に見るとミスが減ります。",
      answeredAt: hoursAgo(68),
      answeredBy: "u-math-b",
    }),
    q({
      id: "q-15",
      studentId: "u-student-3",
      body: "長文読解の段落要旨をまとめるのが遅く、時間切れになります。",
      createdAt: hoursAgo(80),
      subject: "英語",
      topic: "長文読解",
      summary: "長文の段落要旨",
      urgency: "normal",
      recommendedDept: "英語科",
      status: "answered",
      assignedTeacherId: "u-english",
      suggestedTeacherIds: ["u-english"],
      answer: "各段落の最初と最後の文だけ先に読む「骨格読み」を試してください。細部は設問に応じて戻ります。",
      answeredAt: hoursAgo(78),
      answeredBy: "u-english",
    }),
    q({
      id: "q-16",
      studentId: "u-student-4",
      body: "物理の力学で、運動方程式の向きの取り方が毎回迷います。",
      createdAt: hoursAgo(90),
      subject: "理科",
      topic: "物理",
      summary: "運動方程式の向き",
      urgency: "normal",
      recommendedDept: "理科",
      status: "queued",
      assignedTeacherId: "u-science",
      suggestedTeacherIds: ["u-science"],
    }),
    q({
      id: "q-17",
      studentId: "u-student-1",
      body: "二次関数のグラフとx軸の共有点の個数を、判別式で見る問題を復習したいです。",
      createdAt: hoursAgo(100),
      subject: "数学",
      topic: "二次関数",
      summary: "二次関数と判別式",
      urgency: "low",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-a",
      suggestedTeacherIds: ["u-math-a"],
      answer: "D>0 で2つ、D=0 で1つ（接する）、D<0 で共有点なしです。グラフを小さく描く癖をつけると安心です。",
      answeredAt: hoursAgo(98),
      answeredBy: "u-math-a",
    }),
    q({
      id: "q-18",
      studentId: "u-student-2",
      body: "仮定法過去完了と仮定法過去の時制のずれがまだ曖昧です。",
      createdAt: hoursAgo(110),
      subject: "英語",
      topic: "仮定法",
      summary: "仮定法の時制",
      urgency: "normal",
      recommendedDept: "英語科",
      status: "answered",
      assignedTeacherId: "u-english",
      suggestedTeacherIds: ["u-english"],
      answer: "過去の事実と逆なら過去完了（had + 過去分詞）、今と逆なら過去形です。例文を2つ暗記すると安定します。",
      answeredAt: hoursAgo(108),
      answeredBy: "u-english",
    }),
    q({
      id: "q-19",
      studentId: "u-student-3",
      body: "確率の条件付き確率がイメージできません。公式だけ覚えて落ちます。",
      createdAt: hoursAgo(120),
      subject: "数学",
      topic: "確率",
      summary: "条件付き確率",
      urgency: "normal",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-b",
      suggestedTeacherIds: ["u-math-b"],
      answer: "「すでに起きたこと」で分母が変わる、と考えるとよいです。ベン図か表で全体を書いてから公式に入りましょう。",
      answeredAt: hoursAgo(118),
      answeredBy: "u-math-b",
    }),
    q({
      id: "q-20",
      studentId: "u-student-4",
      body: "評論文の主張と例の区別がつかず、現代文の点数が伸びません。",
      createdAt: hoursAgo(130),
      subject: "国語",
      topic: "現代文",
      summary: "評論文の主張と例",
      urgency: "normal",
      recommendedDept: "国語科",
      status: "answered",
      assignedTeacherId: "u-japanese",
      suggestedTeacherIds: ["u-japanese"],
      answer: "「たとえば」「実際」の後は例です。傍線部の前後で筆者の判断が出ている文を主張として印をつけてください。",
      answeredAt: hoursAgo(128),
      answeredBy: "u-japanese",
    }),
    q({
      id: "q-21",
      studentId: "u-student-2",
      body: "二次関数の平行移動で、符号を逆に取る理由がまだしっくりきません。",
      createdAt: hoursAgo(24 * 40),
      subject: "数学",
      topic: "二次関数",
      summary: "二次関数の平行移動",
      urgency: "normal",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-a",
      suggestedTeacherIds: ["u-math-a"],
      answer: "y = (x - p)^2 は右に p です。式の中の符号と、グラフの動きをセットで覚えると間違えにくいです。",
      answeredAt: hoursAgo(24 * 40 - 2),
      answeredBy: "u-math-a",
    }),
    q({
      id: "q-22",
      studentId: "u-student-3",
      body: "二次関数の最大値を平方完成せずに求める方法はありますか。",
      createdAt: hoursAgo(24 * 45),
      subject: "数学",
      topic: "二次関数",
      summary: "二次関数の最大値の別解",
      urgency: "low",
      recommendedDept: "数学科",
      status: "answered",
      assignedTeacherId: "u-math-a",
      suggestedTeacherIds: ["u-math-a"],
      answer: "軸の公式 x = -b/2a を使っても同じです。平方完成はその式の意味を見る手順です。",
      answeredAt: hoursAgo(24 * 45 - 1),
      answeredBy: "u-math-a",
    }),
  ];
}

export function createSeedStore(): StoreData {
  return {
    version: 4,
    users: createSeedUsers(),
    questions: createSeedQuestions(),
  };
}

